on:
  workflow_call:
    inputs:
      instance-url:
        type: string
        description: Salesforce instance URL to log in to as Dev Hub org
        required: false
        default: https://test.salesforce.com
      client-id:
        type: string
        description: OAuth client ID (sometimes called consumer key) of the connected app on Salesforce used to connect to the Dev Hub org
        required: false
        default: 3MVG94RxwSHvjCi_ck.B.2PE8E8BZQlLQy3IW_K4yTalfFY0Lo7X8dbBoL3wqRs17omro_EBKXRYN6SJ8UipQ
      jwt-key-encrypted:
        type: string
        description: Ansible Vault-encrypted private key to connect to the target org with using the JWT flow (this should be encrypted using ansible-vault encrypt, NOT ansible-vault encrypt_string!)
        required: false
        default: |
          $ANSIBLE_VAULT;1.1;AES256
          64353634626137316563313238323936316566316137306664306163643761666335353033623836
          3566353463323762393836653464333663383965363030350a393164313865306665363539616165
          65633230343039313737316161633732323364393135636364636131303563656338636165326634
          3930303761383563650a393832663036386364373738636331323737336332313438376138346666
          63333437383236623133303939656536333434326536363638346638313865623264306639333432
          33366336383064653636616332666263386462393733653163313230373935653737316561656565
          66336239313663353339306538303538376433323731623261306637623363623037343630383436
          64376633393636373265
      username:
        type: string
        description: Username of Salesforce user to authenticate as; must have permission to create scratch orgs
        required: false
        default: classactionsadmin@wtax.co.developer
      run-tests:
        type: boolean
        description: Whether to run tests as part of the deployment. This is required when deploying to a production org.
        required: true
    secrets:
      ansible-vault-password:
        description: Password to be used to decrypt the `jwt-key-encrypted`.
        required: true
jobs:
  deploy:
    uses: wtax-class-actions/wtax-class-actions-github-reusable-workflows/.github/workflows/deploy-sfdx-project.yml@main
    with:
      instance-url: ${{ inputs.instance-url }}
      client-id: ${{ inputs.client-id }}
      username: ${{ inputs.username }}
      jwt-key-encrypted: ${{ inputs.jwt-key-encrypted }}
      run-tests: ${{ inputs.run-tests }}
      destructive-changes-after-deployment: ${{ inputs.destructive-changes-after-deployment }}
    secrets:
      ansible-vault-password: ${{ secrets.ansible-vault-password }}
