on:
  workflow_call:
    inputs:
      instance-url:
        type: string
        description: Salesforce instance URL to log in to as Dev Hub org
        required: false
        default: https://test.salesforce.com
      client-id:
        type: string
        description: OAuth client ID (sometimes called consumer key) of the connected app on Salesforce used to connect to the Dev Hub org
        required: false
        default: 3MVG94RxwSHvjCi_ck.B.2PE8Exa.5CIRPt974udPOxPm0vpnHczVpuRXUNIHb9btvg0SwXUUYi9qoUuRQN8o
      jwt-key-encrypted:
        type: string
        description: Ansible Vault-encrypted private key to connect to the target org with using the JWT flow (this should be encrypted using ansible-vault encrypt, NOT ansible-vault encrypt_string!)
        required: false
        default: |
          $ANSIBLE_VAULT;1.1;AES256
          64353036626632623834636439653738356534396264313337356638373463343935653133633436
          3039666332626436616262343536646331353736343133350a366333666662376130646436616266
          39613232363361366665326131313637396137353464366236313436616361356366633066303935
          6237396233386131340a623630613861626232323830393636326661643262353931386433336636
          64656634393862316539393638383837353964666437383037663334623639386436633138646266
          39303436303636376364623439313162666637613465316635323733343632326233336632643838
          37363666663664663731636538626332383836366130313830646338346132353061373463633238
          37356265623638626439
      username:
        type: string
        description: Username of Salesforce user to authenticate as; must have permission to create scratch orgs
        required: false
        default: classactionsadmin@wtax.co.uat
      run-tests:
        type: boolean
        description: Whether to run tests as part of the deployment. This is required when deploying to a production org.
        required: false
        default: true
      destructive-changes-after-deployment:
        type: boolean
        description: Instruct Salesforce to apply destructive changes (i.e. deletes) after the deployment. This is the default. In some cases you may want to apply destructive changes before deploying. In that case, set this input to false.
        required: false
        default: true
    secrets:
      ansible-vault-password:
        description: Password to be used to decrypt the `jwt-key-encrypted`.
        required: true
jobs:
  deploy:
    uses: wtax-class-actions/wtax-class-actions-github-reusable-workflows/.github/workflows/deploy-sfdx-project.yml@main
    with:
      instance-url: ${{ inputs.instance-url }}
      client-id: ${{ inputs.client-id }}
      username: ${{ inputs.username }}
      jwt-key-encrypted: ${{ inputs.jwt-key-encrypted }}
      run-tests: ${{ inputs.run-tests }}
      destructive-changes-after-deployment: ${{ inputs.destructive-changes-after-deployment }}
    secrets:
      ansible-vault-password: ${{ secrets.ansible-vault-password }}
